version: "3.8"
services:
  db:
    image: postgres:16.0
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  backend:
    build: ./server/allTheMethods
    ports:
      - 8080:8080
    environment:
      - DB_URL= jdbc:postgresql://db/solverAppDB
    
  
  frontend:
    build: ./clientside
    ports:
      - 5173:80

