spring.application.name=allTheMethods

spring.datasource.url=jdbc:postgresql://localhost:5432/solverAppDB
spring.datasource.username=postgres
spring.datasource.password=nad9mate50%
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=false



spring.app.jwtSecret=secretKey12398fdsiofjdisovjdfiovmewprfiewopfkmcakdopewuriopwmc
spring.app.jwtExpirationMs=300000000
