spring.application.name=allTheMethods
spring.datasource.url=jdbc:postgresql://localhost:5432/solverAppDB
spring.datasource.username=postgres
spring.datasource.password=nad9mate50%


spring.jpa.hibernate.ddl-auto=update
